development:
  adapter: postgresql
  database: ipp_development
  host: localhost
  encoding: unicode
  pool: 5
  timeout: 5000
  username: postgres
  password: "qweqweqwe"

test:
  adapter: postgresql
  database: ipp_test
  host: localhost
  encoding: unicode
  pool: 5
  timeout: 5000
  username: postgres
  password: "qweqweqwe"
